setup

diff --git a/.github/workflows/unit-test.yaml b/.github/workflows/unit-test.yaml
--- a/.github/workflows/unit-test.yaml
+++ b/.github/workflows/unit-test.yaml
@@ -58,8 +58,31 @@ jobs:
         env:
           GITHUB_ACTIONS_STAGE: "UNIT_TESTS"
           PACKAGE_NAMES: "./helpers/validate"
+      - if: (success() || failure())
+        name: Prepare datadog-ci
+        continue-on-error: true
+        run: |
+          if type datadog-ci > /dev/null 2>&1; then
+            exit 0
+          fi
+          # Curl does not always exit 1 if things go wrong. To determine if this is successful we'll
+          # we'll silence all non-error output and check the results to determine success.
+          if ! out="$(curl -sSL --fail https://github.com/DataDog/datadog-ci/releases/download/v5.4.0/datadog-ci_linux-x64 --output /usr/local/bin/datadog-ci 2>&1)"; then
+            printf "failed to download datadog-ci: %s" "$out"
+          fi
+          if [[ -n "$out" ]]; then
+            printf "failed to download datadog-ci: %s" "$out"
+          fi
+          chmod +x /usr/local/bin/datadog-ci
+
       - name: Beam up
-        run: datadog-ci junit upload --service "$GITHUB_REPOSITORY" ./gotestsum-report.xml
+        run: |
+            export DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }}
+            if [[ -z "$DATADOG_API_KEY ]]; then
+              echo "where is the key"
+              exit 2
+            fi
+            datadog-ci junit upload --service "$GITHUB_REPOSITORY" ./gotestsum-report.xml
 
   save-artifacts-on-fail:
     needs: test
